### ISSUE TITLE
tagOpened cannot handle half-open-tag

### ISSUE THREAD

**Issue by macdao** [shenjunru/LazyWrite#6]
this is real code from doubleclick

```javascript
document.write ("<scr"+"ipt type='text/javascript' src='");
document.write ("does-not-matter.js");
document.write ("'></scr"+"ipt>");
```

it will render `<script type="text/javascript" src="does-not-matter.js"></script>` using original document.write which is what I expected.

Any idea folks?

**Comment by shenjunru** [comment]
This should be fixed. Hope it works for you.
Thank you for the report.

**Comment by macdao** [comment]
AMAZING EFFICIENT!!
